apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapi-deployment
  labels:
    app: votingapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingapi
  template:
    metadata:
      labels:
        app: votingapi
    spec:
      containers:
        - name: votingapi
          image: votingacr.azurecr.io/votingapi:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80  # ✅ Use non-root port
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: ASPNETCORE_URLS  # ✅ Add this
              value: "http://*:5000"
            - name: DatabaseSettings__ConnectionString
              valueFrom:
                configMapKeyRef:
                  name: mongo-configmap
                  key: connection_string
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          securityContext:
            runAsUser: 0                 # Add this to run as root user
            allowPrivilegeEscalation: true
      imagePullSecrets:
        - name: acr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: votingapi-service
spec:
  selector:
    app: votingapi
  ports:
    - protocol: TCP
      port: 80          #  Exposed service port
      targetPort: 80  #  Container port
