
apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingclient-deployment
  labels:
    app: votingclient
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingclient
  template:
    metadata:
      labels:
        app: votingclient
    spec:
      containers:
        - name: votingclient
          image: akki0049/votingapp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Development
            - name: votingAPIUrl
              valueFrom:
                  configMapKeyRef:
                    name: votingapi-configmap
                    key: votingapi_url
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: votingclient-service
spec:
  type: NodePort
  selector:
    app: votingclient
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8080
      nodePort: 30000