services:
  voting.api:
    container_name: votingapi
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - "DatabaseSettings:ConnectionString=mongodb://votingdb:27017"
    depends_on:
      - voting.db
    ports:
      - "8000:80"

  voting.client:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - VotingAPIUrl=http://votingapi:8080
      - ASPNETCORE_HTTP_PORTS=8080
    depends_on:
      - voting.db
      - voting.api
    ports:
      - "8001:80"

  voting.db: 
    container_name: votingdb
    restart: always
    ports:
      - "27017:27017"
    volumes: 

      - ${WEBAPP_STORAGE_HOME}/site:/data/db